Repository BCG-X-Official/facet, pull requests merged in 2021-01, with the labels that each got.

#192 fix incompatibilities causing tests to fail in minimal and/or unconstrained builds
  test/test/facet/test_inspection.py
  test/test/facet/test_validation.py
Labels: bug

#193 remove local develop pointers from a nb
  pyproject.toml
  sphinx/source/tutorial/Water_Drilling_Incident_Classification_with_Facet.ipynb
Labels: documentation

#195 downgrade condabuild to 3.20.*; restore other environment upgrades
  environment.yml
Labels: bug, release

#196 DOC: fix docstring references to sklearndf
  src/facet/selection/_selection.py
Labels: bug, documentation

#197 catch up with latest changes for release 1.0.1 pipeline
  azure-pipelines.yml
  environment.yml
  pyproject.toml
  src/facet/selection/_selection.py
Labels: release

#203 replace dataset in quickstart guide
  README.rst
  sphinx/auxiliary/Boston_getting_started_example.ipynb
  sphinx/auxiliary/Diabetes_getting_started_example.ipynb
  sphinx/auxiliary/diabetes_quickstart.csv
  sphinx/source/_static/ranker_summary.png
  sphinx/source/_static/redundancy_dendrogram.png
  sphinx/source/_static/redundancy_matrix.png
  sphinx/source/_static/simulation_output.png
  sphinx/source/_static/synergy_matrix.png
Labels: bug

#204 Release/1.0.1
  README.rst
  sphinx/auxiliary/Boston_getting_started_example.ipynb
  sphinx/auxiliary/Diabetes_getting_started_example.ipynb
  sphinx/auxiliary/diabetes_quickstart.csv
  sphinx/source/_static/ranker_summary.png
  sphinx/source/_static/redundancy_dendrogram.png
  sphinx/source/_static/redundancy_matrix.png
  sphinx/source/_static/simulation_output.png
  sphinx/source/_static/synergy_matrix.png
Labels: bug

#199 update the environment.yml
  environment.yml
Labels: CI

#201 rename branch 1.1 to 1.1.x
  README.rst
  azure-pipelines.yml
  environment.yml
  pyproject.toml
  sphinx/auxiliary/Boston_getting_started_example.ipynb
  sphinx/auxiliary/Diabetes_getting_started_example.ipynb
  sphinx/auxiliary/diabetes_quickstart.csv
  sphinx/source/_static/ranker_summary.png
  sphinx/source/_static/redundancy_dendrogram.png
  sphinx/source/_static/redundancy_matrix.png
  sphinx/source/_static/simulation_output.png
  sphinx/source/_static/synergy_matrix.png
  src/facet/selection/_selection.py
Labels: CI

#208 fix typo: change 'childs' to 'children'
  test/test/test_docs.py
Labels: bug, documentation

#209 remove a print() statement accidentally left in after debugging
  src/facet/selection/_selection.py
Labels: bug

#211 BUILD: add veracode scanning to pipeline
  azure-pipelines.yml
Labels: CI

#213 API: support shap v0.34 up to v0.37 via new BaseEstimator stub class
  pyproject.toml
  src/facet/inspection/_explainer.py
  src/facet/inspection/_shap.py
Labels: enhancement

#214 REFACTOR: update parallelization code to use new Job classes
  src/facet/crossfit/_crossfit.py
  src/facet/inspection/_shap.py
  src/facet/selection/_selection.py
  src/facet/simulation/_simulation.py
  test/test/facet/test_inspection.py
Labels: refactor

#212 FIX: update filepath and provide stage name
  azure-pipelines.yml
Labels: CI/CD, bug

#217 BUILD: update version numbers
  sphinx/source/faqs.rst
  src/facet/__init__.py
Labels: CI/CD

#219 DOC: parallelise LearnerInspector in getting started example
  README.rst
  sphinx/auxiliary/Diabetes_getting_started_example.ipynb
  sphinx/source/tutorial/Predictive_Maintenance_Regression_with_Facet.ipynb
Labels: documentation

#221 BUILD: bump version to 1.0.2
  pyproject.toml
  sphinx/source/faqs.rst
  src/facet/__init__.py
Labels: CI/CD

#222 BUILD: do not build and publish documentation in nightly builds
  azure-pipelines.yml
Labels: CI/CD

#223 BUILD: add conda-verify
  azure-pipelines.yml
  condabuild/meta.yaml
Labels: CI/CD
