Repository BCG-X-Official/facet, pull requests merged in 2021-02, with the labels that each got.

#225 BUILD: bugfix detection of build changes
  azure-pipelines.yml
Labels: CI/CD, bug

#228 BUILD: eliminate unconstrained build from pipeline
  azure-pipelines.yml
  pyproject.toml
Labels: CI/CD, bug

#226 BUILD: do not run nightly builds on weekends
  azure-pipelines.yml
Labels: CI/CD

#224 BUILD: align build requirements pyproject.toml/meta.yaml/tox.ini & across repos
  azure-pipelines.yml
  condabuild/meta.yaml
  environment.yml
  pyproject.toml
  tox.ini
Labels: CI/CD

#229 BUILD: increase minimum pytools version to 1.1
  pyproject.toml
Labels: CI/CD

#230 BUILD: update environment.yml
  azure-pipelines.yml
  environment.yml
  pyproject.toml
Labels: CI/CD

#231 BUILD: update veracode scan version to point to BuildID
  azure-pipelines.yml
Labels: CI/CD

#232 FIX: fix min version spec for gamma-pytools
  pyproject.toml
Labels: CI/CD, bug

#233 BUILD: optimize conda build config
  condabuild/meta.yaml
Labels: CI/CD

#234 FIX: fix a syntax error introduced to a bash script in the pipeline
  azure-pipelines.yml
Labels: CI/CD, bug

#235 FIX: apply color scheme to histogram of simulation matplot style
  src/facet/simulation/viz/_style.py
Labels: enhancement, sequential

#236 API: make method MatplotStyle._apply_color_scheme public
  src/facet/simulation/viz/_style.py
Labels: enhancement, sequential

#237 DOC: add doc links for FACET and sklearndf
  README.rst
Labels: documentation

#238 DOC: update header to align with other notebooks
  sphinx/auxiliary/Diabetes_getting_started_example.ipynb
Labels: documentation

#240 BUILD: use regular pytest & pytest-cov, run pytest nightly
  azure-pipelines.yml
Labels: CI/CD, bug

#242 DOC: restore Azure pipeline git badge
  README.rst
Labels: documentation

#243 API: rename LearnerInspector.features to .features_
  src/facet/inspection/_inspection.py
  test/test/facet/test_shap_decomposition.py
Labels: refactor

#246 BUILD: add support for shap v0.38.*
  environment.yml
  pyproject.toml
  src/facet/inspection/_explainer.py
  src/facet/inspection/_shap.py
Labels: CI/CD, enhancement

#244 API: replace SHAP vector decomposition with SHAP vector projection
  src/facet/inspection/_inspection.py
  src/facet/inspection/_shap_decomposition.py
  src/facet/inspection/_shap_global_explanation.py
  src/facet/inspection/_shap_projection.py
  test/test/facet/test_inspection.py
  test/test/facet/test_shap_decomposition.py
Labels: enhancement

#249 change version to 1.1.0rc0
  src/facet/__init__.py
Labels: CI/CD
