Repository BCG-X-Official/facet, pull requests merged in 2021-03, with the labels that each got.

#250 API: remove the experimental 'shuffle_features' option
  src/facet/crossfit/_crossfit.py
  src/facet/selection/_selection.py
  src/facet/validation/_validation.py
  test/test/conftest.py
  test/test/facet/test_inspection.py
  test/test/facet/test_simulation.py
Labels: enhancement

#247 TEST: re-enable unit test for docstrings
  condabuild/meta.yaml
  pyproject.toml
  src/facet/crossfit/_crossfit.py
  src/facet/inspection/_explainer.py
  src/facet/inspection/_inspection.py
  src/facet/inspection/_shap.py
  src/facet/inspection/_shap_global_explanation.py
  src/facet/selection/_selection.py
  src/facet/simulation/_simulation.py
  src/facet/simulation/partition/_partition.py
  src/facet/simulation/viz/_draw.py
  src/facet/simulation/viz/_style.py
  src/facet/validation/_validation.py
  test/test/test_docs.py
  tox.ini
Labels: CI/CD, documentation

#248 FIX: downgrade scipy to 1.5.* in environment.yml
  environment.yml
Labels: CI/CD, bug

#253 DOCS: add pre-commit hook instructions to contribution guide
  sphinx/source/contribution_guide.rst
Labels: documentation

#251 DOC: add release notes for 1.0.2
  README.rst
  RELEASE_NOTES.rst
  sphinx/source/.gitignore
  sphinx/source/api_landing.rst
  sphinx/source/index.rst
Labels: documentation

#254 BUILD: update azure-pipelines.yml for releasing
  azure-pipelines.yml
  pyproject.toml
  src/facet/__init__.py
  test/test/test_package_version.py
Labels: CI/CD

#256 BUILD: update flake8 to v3.9.0
  .pre-commit-config.yaml
  azure-pipelines.yml
  environment.yml
Labels: CI/CD

#257 FIX: do not export constants and type aliases
  pyproject.toml
  src/facet/crossfit/_crossfit.py
  src/facet/simulation/_simulation.py
  test/test/facet/test_simulation.py
Labels: bug, enhancement, sequential

#258 RELEASE: facet 1.0.2rc0
  .pre-commit-config.yaml
  LICENSE
  README.rst
  RELEASE_NOTES.rst
  azure-pipelines.yml
  condabuild/meta.yaml
  environment.yml
  pyproject.toml
  sphinx/auxiliary/Diabetes_getting_started_example.ipynb
  sphinx/source/.gitignore
  sphinx/source/api_landing.rst
  sphinx/source/contribution_guide.rst
  sphinx/source/faqs.rst
  sphinx/source/index.rst
  sphinx/source/tutorial/Predictive_Maintenance_Regression_with_Facet.ipynb
  src/facet/__init__.py
  src/facet/inspection/_explainer.py
  src/facet/inspection/_shap.py
  src/facet/selection/_selection.py
  src/facet/simulation/viz/_style.py
  test/test/test_package_version.py
  tox.ini
Labels: release

#259 BUILD: set package version to 1.0.2
  pyproject.toml
  src/facet/__init__.py
Labels: release

#260 RELEASE: facet 1.0.2
  pyproject.toml
  src/facet/__init__.py
Labels: release

#255 Finalize revised calculation approach
  RELEASE_NOTES.rst
  src/facet/inspection/_inspection.py
  src/facet/inspection/_shap.py
  src/facet/inspection/_shap_decomposition.py
  src/facet/inspection/_shap_global_explanation.py
  src/facet/inspection/_shap_projection.py
  test/test/conftest.py
  test/test/facet/test_inspection.py
Labels: enhancement

#263 API: move package facet.simulation.partition to facet.data.partition
  README.rst
  sphinx/auxiliary/Diabetes_getting_started_example.ipynb
  sphinx/source/tutorial/Classification_with_Facet.ipynb
  sphinx/source/tutorial/Model_simulation_deep_dive.ipynb
  sphinx/source/tutorial/Predictive_Maintenance_Regression_with_Facet.ipynb
  sphinx/source/tutorial/Water_Drilling_Incident_Classification_with_Facet.ipynb
  src/facet/data/partition/__init__.py
  src/facet/data/partition/_partition.py
  src/facet/simulation/_simulation.py
  src/facet/simulation/partition/__init__.py
  test/test/facet/test_partition.py
  test/test/facet/test_simulation.py
Labels: enhancement

#264 API: rename JobQueue.start() to JobQueue.on_run()
  src/facet/crossfit/_crossfit.py
Labels: API

#261 BUILD: add support for shap v0.39
  RELEASE_NOTES.rst
  environment.yml
  pyproject.toml
  src/facet/inspection/_explainer.py
Labels: build

#267 BUILD: update dependencies in pyproject.toml
  pyproject.toml
Labels: build

#268 BUILD: add copy of old docs-versions folder
  azure-pipelines.yml
Labels: build

#269 BUILD: Release facet 1.1.0rc0
  README.rst
  RELEASE_NOTES.rst
  azure-pipelines.yml
  condabuild/meta.yaml
  environment.yml
  pyproject.toml
  sphinx/auxiliary/Diabetes_getting_started_example.ipynb
  sphinx/source/faqs.rst
  sphinx/source/tutorial/Classification_with_Facet.ipynb
  sphinx/source/tutorial/Model_simulation_deep_dive.ipynb
  sphinx/source/tutorial/Predictive_Maintenance_Regression_with_Facet.ipynb
  sphinx/source/tutorial/Water_Drilling_Incident_Classification_with_Facet.ipynb
  src/facet/__init__.py
  src/facet/crossfit/_crossfit.py
  src/facet/data/partition/__init__.py
  src/facet/data/partition/_partition.py
  src/facet/inspection/_explainer.py
  src/facet/inspection/_inspection.py
  src/facet/inspection/_shap.py
  src/facet/inspection/_shap_decomposition.py
  src/facet/inspection/_shap_global_explanation.py
  src/facet/inspection/_shap_projection.py
  src/facet/selection/_selection.py
  src/facet/simulation/_simulation.py
  src/facet/simulation/partition/__init__.py
  src/facet/simulation/viz/_draw.py
  src/facet/simulation/viz/_style.py
  src/facet/validation/_validation.py
  test/test/conftest.py
  test/test/facet/test_inspection.py
  test/test/facet/test_partition.py
  test/test/facet/test_shap_decomposition.py
  test/test/facet/test_simulation.py
  test/test/test_docs.py
  tox.ini
Labels: release

#273 BUILD: set facet version to 1.1.0
  src/facet/__init__.py
Labels: build

#272 REFACTOR: tweak code and docstrings of class LearnerInspector
  src/facet/inspection/_inspection.py
Labels: refactor

#271 API: add hidden option to fit the LearnerInspector once on the full sample
  src/facet/inspection/_inspection.py
  src/facet/inspection/_shap.py
  test/test/facet/test_inspection.py
Labels: API

#270 REFACTOR: fit on the full sample as part of the crossfit's Job queue
  src/facet/crossfit/_crossfit.py
Labels: refactor

#274 API: output shap values of the positive class for binary classifiers
  RELEASE_NOTES.rst
  src/facet/inspection/_shap.py
  test/test/facet/test_inspection.py
Labels: API

#265 DOC: update the tutorial notebooks
  README.rst
  sphinx/auxiliary/Diabetes_getting_started_example.ipynb
  sphinx/source/_static/ranker_summary.png
  sphinx/source/_static/redundancy_dendrogram.png
  sphinx/source/_static/redundancy_matrix.png
  sphinx/source/_static/simulation_output.png
  sphinx/source/_static/synergy_matrix.png
  sphinx/source/tutorial/Classification_with_Facet.ipynb
  sphinx/source/tutorial/Model_simulation_deep_dive.ipynb
  sphinx/source/tutorial/Predictive_Maintenance_Regression_with_Facet.ipynb
  sphinx/source/tutorial/Scikit-learn_classifier_summaries_using_FACET.ipynb
  sphinx/source/tutorial/Synergy_Redundancy_Tutorial_with_Facet.ipynb
  sphinx/source/tutorial/Water_Drilling_Incident_Classification_with_Facet.ipynb
  sphinx/source/tutorial/classification_sim2.csv
  sphinx/source/tutorial/classification_sim2_cvcurve.csv
  sphinx/source/tutorial/gas_turbine_data.txt
  sphinx/source/tutorial/regression_sim1.csv
  sphinx/source/tutorials.rst
Labels: documentation

#276 FIX: make class _FitModelOnFullData a global class to fix Python 3.6 pickling
  src/facet/crossfit/_crossfit.py
Labels: bug

#278 DOC: add release notes for FACET 1.0.3
  RELEASE_NOTES.rst
Labels: documentation
