Repository BCG-X-Official/facet, pull requests merged in 2022-03, with the labels that each got.

#330 API: make method FittableMixin.ensure_fitted public
  src/facet/data/partition/_partition.py
  src/facet/inspection/_inspection.py
  src/facet/inspection/_shap.py
  src/facet/inspection/_shap_projection.py
  src/facet/selection/_selection.py
  src/facet/selection/base/_parameters.py
Labels: API

#329 BUILD: update black to v22.1
  .pre-commit-config.yaml
  azure-pipelines.yml
  environment.yml
  src/facet/inspection/_inspection.py
  src/facet/inspection/_shap_global_explanation.py
  src/facet/inspection/_shap_projection.py
Labels: build

#324 BUILD: add support for mypy
  .pre-commit-config.yaml
  azure-pipelines.yml
  environment.yml
  mypy.ini
  src/facet/data/partition/_partition.py
  src/facet/inspection/_explainer.py
  src/facet/inspection/_inspection.py
  src/facet/inspection/_shap.py
  src/facet/inspection/_shap_global_explanation.py
  src/facet/inspection/_shap_projection.py
  src/facet/py.typed
  src/facet/selection/_parameters.py
  src/facet/selection/_selection.py
  src/facet/selection/base/_parameters.py
  src/facet/simulation/_simulation.py
  src/facet/simulation/viz/_draw.py
  src/facet/simulation/viz/_style.py
Labels: build

#331 DOC: finalize API documentation for 2.0 release
  src/facet/data/_sample.py
  src/facet/data/partition/_partition.py
  src/facet/inspection/_explainer.py
  src/facet/inspection/_inspection.py
  src/facet/inspection/_shap.py
  src/facet/inspection/_shap_global_explanation.py
  src/facet/selection/_parameters.py
  src/facet/selection/_selection.py
  src/facet/simulation/_simulation.py
  src/facet/simulation/viz/_draw.py
  src/facet/simulation/viz/_style.py
  test/test/facet/test_selection.py
Labels: documentation
