Repository BCG-X-Official/facet, pull requests merged in 2023-05, with the labels that each got.

#360 BUILD: use micromamba to solve environment.yml
  .pre-commit-config.yaml
  azure-pipelines.yml
  environment.yml
  pyproject.toml
  src/facet/inspection/_learner_inspector.py
  src/facet/selection/_selection.py
  test/test/conftest.py
  test/test/facet/test_inspection.py
  test/test/facet/test_selection.py
Labels: build

#361 FIX: remove contravariant from `T_Model`
  src/facet/inspection/_explainer.py
  src/facet/inspection/_function_inspector.py
  src/facet/inspection/_types.py
Labels: bug, refactor

#352 API: factor out abstract base class `ModelInspector` from `LearnerInspector`, and introduce new `FunctionInspector`
  README.rst
  environment.yml
  pyproject.toml
  sphinx/auxiliary/Diabetes_getting_started_example.ipynb
  sphinx/source/tutorial/Classification_with_Facet.ipynb
  src/facet/inspection/__init__.py
  src/facet/inspection/_explainer.py
  src/facet/inspection/_function_inspector.py
  src/facet/inspection/_inspection.py
  src/facet/inspection/_learner_inspector.py
  src/facet/inspection/_model_inspector.py
  src/facet/inspection/_shap.py
  src/facet/inspection/_shap_context.py
  src/facet/inspection/_shap_projection.py
  src/facet/inspection/_types.py
  src/facet/inspection/shap/__init__.py
  src/facet/inspection/shap/_function.py
  src/facet/inspection/shap/_shap.py
  src/facet/inspection/shap/sklearn/__init__.py
  src/facet/inspection/shap/sklearn/_sklearn.py
  src/facet/selection/_parameters.py
  src/facet/selection/base/_parameters.py
  src/facet/simulation/_result.py
  src/facet/simulation/base/_base.py
  test/test/conftest.py
  test/test/facet/test_inspection.py
  test/test/facet/test_shap_decomposition.py
Labels: API

#363 REFACTOR: move explainer classes to dedicated `explainer` sub-package
  RELEASE_NOTES.rst
  src/facet/_types.py
  src/facet/explanation/__init__.py
  src/facet/explanation/_explanation.py
  src/facet/explanation/_types.py
  src/facet/explanation/base/__init__.py
  src/facet/explanation/base/_base.py
  src/facet/explanation/parallel/__init__.py
  src/facet/explanation/parallel/_parallel.py
  src/facet/inspection/__init__.py
  src/facet/inspection/_explainer.py
  src/facet/inspection/_function_inspector.py
  src/facet/inspection/_learner_inspector.py
  src/facet/inspection/_types.py
  src/facet/inspection/base/__init__.py
  src/facet/inspection/base/_model_inspector.py
  src/facet/inspection/shap/_function.py
  src/facet/inspection/shap/_shap.py
  src/facet/inspection/shap/sklearn/_sklearn.py
  test/test/facet/test_inspection.py
  test/test/facet/test_shap_decomposition.py
Labels: API, refactor

#362 BUILD: release FACET 2.0.0
  .pre-commit-config.yaml
  README.rst
  RELEASE_NOTES.rst
  azure-pipelines.yml
  condabuild/meta.yaml
  environment.yml
  mypy.ini
  pyproject.toml
  sphinx/auxiliary/Diabetes_getting_started_example.ipynb
  sphinx/source/tutorial/Classification_with_Facet.ipynb
  src/facet/__init__.py
  src/facet/_types.py
  src/facet/data/partition/_partition.py
  src/facet/explanation/__init__.py
  src/facet/explanation/_explanation.py
  src/facet/explanation/_types.py
  src/facet/explanation/base/__init__.py
  src/facet/explanation/base/_base.py
  src/facet/explanation/parallel/__init__.py
  src/facet/explanation/parallel/_parallel.py
  src/facet/inspection/__init__.py
  src/facet/inspection/_explainer.py
  src/facet/inspection/_function_inspector.py
  src/facet/inspection/_inspection.py
  src/facet/inspection/_learner_inspector.py
  src/facet/inspection/_shap.py
  src/facet/inspection/_shap_context.py
  src/facet/inspection/_shap_projection.py
  src/facet/inspection/base/__init__.py
  src/facet/inspection/base/_model_inspector.py
  src/facet/inspection/shap/__init__.py
  src/facet/inspection/shap/_function.py
  src/facet/inspection/shap/_shap.py
  src/facet/inspection/shap/sklearn/__init__.py
  src/facet/inspection/shap/sklearn/_sklearn.py
  src/facet/selection/_parameters.py
  src/facet/selection/_selection.py
  src/facet/selection/base/_parameters.py
  src/facet/simulation/_result.py
  src/facet/simulation/base/_base.py
  test/test/conftest.py
  test/test/facet/test_inspection.py
  test/test/facet/test_selection.py
  test/test/facet/test_shap_decomposition.py
Labels: release

#365 BUILD: use mamba for faster conda builds
  azure-pipelines.yml
Labels: build
